# Generated by Django 5.0.7 on 2024-07-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full time', 'Full Time'), ('Part time', 'Part Time')], max_length=15),
        ),
    ]
