# Generated by Django 5.0.7 on 2024-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_salary_job_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experiences',
            field=models.IntegerField(default=1),
        ),
    ]
