# Generated by Django 4.2.14 on 2024-07-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv_upload',
            field=models.FileField(blank=True, default='Choice file', max_length=340, null=True, upload_to='apply/'),
        ),
    ]
